### ISSUE TITLE
solr conf

### ISSUE THREAD

**Issue by wacharlin** [DmitryKey/bert-solr-search#12]
I followed the steps given in `"https://github.com/DmitryKey/solr-vector-scoring“`  to configure the solr plugin on the automatically generated configuration file, and the vector can indeed be stored. The vector plugin part is configured. However, the query operation performed under solr admin does not work well, and there are almost no search results. After that, I used the solr configuration you gave and found that the query works very well. I found that your solr configuration is different from the default. So can you elaborate on your solr configuration process? Or give the part that can strengthen the query？thank you.
![image](https://user-images.githubusercontent.com/38215077/114292328-55dedf80-9ac0-11eb-9eaf-e83a27ef409f.png)
![image](https://user-images.githubusercontent.com/38215077/114292351-7444db00-9ac0-11eb-9999-e4a946367780.png)

**Comment by wacharlin** [comment]
I solved it.

**Comment by DmitryKey** [comment]
@wacharlin thanks! One suggestion: let's keep the discussion in the same tickets, if possible. This will help to avoid duplicates!


Can you share more info on your solution?

Also, it is worth to mention, that the main purpose of this repo is not keyword search: instead of searching keywords, we are searching vectors computed from these keywords using BERT / SBERT.

**Comment by wacharlin** [comment]
I just modify the solrconfig.xml,replace the "text" (in  <initParams>) to "_text_".I just tried, but I didn't think I could and I don't know why. thank you!

**Comment by DmitryKey** [comment]
@wacharlin do you mean you replaced single quote with double quote?

**Comment by wacharlin** [comment]
because "\_text\_"corresponds to your field you defined.
