### ISSUE TITLE
about request.get and post.

### ISSUE THREAD

**Issue by wacharlin** [DmitryKey/bert-solr-search#15]
![image](https://user-images.githubusercontent.com/38215077/119986394-5d1d6680-bff6-11eb-952a-b8bed46be919.png)
hi,I want to know how to update solr? I don't know the meaning of the code.if I want to push data to solr,I should execute the function about commit() and use requests.get(), why i can't use post? and what is the meaning of the flush() and commit()?
could you please teach me? thank you.

**Comment by DmitryKey** [comment]
hey @wacharlin 

POST is made for sending large request bodies, that don't fit in GET: https://stackoverflow.com/a/2659995/158328

for flush() you need to use POST, because `/update` end-point accepts docs in the form of input JSON. You can send in thousands of documents (if your server side is ok with that) => gotta use POST.
This method makes sure your documents-to-be-indexed reach the Solr server and get stored in some Solr data structure (disk and / or memory).

for commit() you really don't need POST, because GET is perfectly enough for the short url string.
This method makes your newly added documents searchable.

**Comment by wacharlin** [comment]
thank you.I get it.but I want to know could you please teach me  the using of the solr about '`/update`' ?because I don't find some instructions about `/update`,so I don't know the meaning of `commit=true`. although I know by your  teaching,where can I learn more about `/update` and its `parameter` like '`commit=true'`?  thank you!

**Comment by wacharlin** [comment]
Hi, @DmitryKey ,I want to know function` to_solr_vector`.why use this format ?`1|point_1 2|point_2 ... n|point_n`

**Comment by DmitryKey** [comment]
hi @wacharlin 

Updating:
https://solr.apache.org/guide/8_0/uploading-data-with-index-handlers.html#json-formatted-index-updates

Committing: 
https://solr.apache.org/guide/8_0/updatehandlers-in-solrconfig.html

**Comment by DmitryKey** [comment]
To your second question about to_solr_vector() method. It is because we define `VectorField` type as the pipeline of two steps:

1. solr.WhitespaceTokenizerFactory splits input string by spaces
2. solr.DelimitedPayloadTokenFilterFactory, which
Under the hood the solr.DelimitedPayloadTokenFilter uses DelimitedPayloadTokenFilter and it encodes anything to the right of the payload delimiter | in the requested format (float). And this data structure is sent to Lucene index for the given document.

For reference:

     <fieldType name="VectorField" class="solr.TextField" indexed="true" termOffsets="true" stored="true" termPayloads="true" termPositions="true" termVectors="true" storeOffsetsWithPositions="true">
    <analyzer>
      <tokenizer class="solr.WhitespaceTokenizerFactory"/>
      <filter class="solr.DelimitedPayloadTokenFilterFactory" encoder="float"/>
    </analyzer>
  </fieldType>


All of this and more is documented in my blog post: https://medium.com/swlh/fun-with-apache-lucene-and-bert-embeddings-c2c496baa559
